"use client";
import "./globals.css";
import type { Metadata } from "next";
import inPageNav from "./components/navbar/inPageNav";
import { Inter, Roboto, Poppins, Raleway, Nunito } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });
const nunito = Nunito({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body className="animate__animated">
        <>
          <style jsx global>{`
            :root {
              --raleway-font: ${raleway.style.fontFamily};
              --nunito-font: ${nunito.style.fontFamily};
              --roboto-font: ${roboto.style.fontFamily};
              --inter-font: ${inter.style.fontFamily};
            }
          `}</style>
          {/* <Navbar /> */}
          <div className="bodyContainer">{children}</div>
        </>
      </body>
    </html>
  );
}
