"use client";
import "./globals.css";
import type { Metadata } from "next";
// import inPageNav from "./components/navbar/inPageNav";
import { Inter, Roboto, Poppins, Raleway, Nunito } from "next/font/google";
import footerImg from "../../public/images/footerImg.png";
import Image from "next/image";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </head>
      <body className="animate__animated">
        <>
          <style jsx global>{`
            :root {
              --raleway-font: ${raleway.style.fontFamily};
              --nunito-font: ${nunito.style.fontFamily};
              --roboto-font: ${roboto.style.fontFamily};
              --inter-font: ${inter.style.fontFamily};
            }
          `}</style>
          {/* <Navbar /> */}
          <div className="bodyContainer">{children}</div>
          <div className="footerContainer">
            <Image src={footerImg} alt={"footer image"} className="footerImg" />
          </div>
        </>
      </body>
    </html>
  );
}
